version: '3'

services:
  mailhog:
      container_name: mailhog
      image: mailhog/mailhog
      networks:
        local:
      ports:
        - '1025:1025'
        - '8025:8025'

  cfml:
    container_name: cfml
    image: ortussolutions/commandbox:adobe2018
    environment:
      cfconfig_adminPassword: password
      cfconfigfile: myconfig.json
    depends_on:
      - mailhog
    networks:
      local:
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}:/app

networks:
  local:
    driver: bridge
